///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DashboardAutomation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DashboardAutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("35f002a1-ef3b-4e9c-98d4-09d5c83f1135")]
    public partial class DashboardAutomationRepository : RepoGenBaseFolder
    {
        static DashboardAutomationRepository instance = new DashboardAutomationRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DashboardAutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("35f002a1-ef3b-4e9c-98d4-09d5c83f1135")]
        public static DashboardAutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DashboardAutomationRepository() 
            : base("DashboardAutomationRepository", "/", null, 0, false, "35f002a1-ef3b-4e9c-98d4-09d5c83f1135", ".\\RepositoryImages\\DashboardAutomationRepository35f002a1.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("35f002a1-ef3b-4e9c-98d4-09d5c83f1135")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DashboardAutomationRepositoryFolders
    {
    }
#pragma warning restore 0436
}
