///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsDataProfile
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateGeneralSettings recording.
    /// </summary>
    [TestModule("32b238bf-c33d-43ec-b815-4b4b8e247497", ModuleType.Recording, 1)]
    public partial class CreateGeneralSettings : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static CreateGeneralSettings instance = new CreateGeneralSettings();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateGeneralSettings()
        {
            dataName = "";
            varItemType = "";
            varItemReport = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateGeneralSettings Instance
        {
            get { return instance; }
        }

#region Variables

        string _dataName;

        /// <summary>
        /// Gets or sets the value of variable dataName.
        /// </summary>
        [TestVariable("c0349105-59a2-4217-8d3e-ad1f58310804")]
        public string dataName
        {
            get { return _dataName; }
            set { _dataName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varItemType.
        /// </summary>
        [TestVariable("011758ba-82f4-430f-9f38-df0b41527783")]
        public string varItemType
        {
            get { return repo.varItemType; }
            set { repo.varItemType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varItemReport.
        /// </summary>
        [TestVariable("ba525e2f-cd9e-47c9-a2f6-d8ed1546f584")]
        public string varItemReport
        {
            get { return repo.varItemReport; }
            set { repo.varItemReport = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.Administers.AddNew' at Center.", repo.TestArchitect.Administers.AddNewInfo, new RecordItemIndex(0));
            repo.TestArchitect.Administers.AddNew.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName' at Center.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileNameInfo, new RecordItemIndex(1));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$dataName' on item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName'.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileNameInfo, new RecordItemIndex(2));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName.Element.SetAttributeValue("Value", dataName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$varItemType' on item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbItemType'.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbItemTypeInfo, new RecordItemIndex(3));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbItemType.Element.SetAttributeValue("TagValue", varItemType);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute TagValue to '$varItemReport' on item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbSubReport'.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbSubReportInfo, new RecordItemIndex(4));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.CbbSubReport.Element.SetAttributeValue("TagValue", varItemReport);
            Delay.Milliseconds(0);
            
            Mouse_Click_ChkDistinct(repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.ChkDistinctInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.ButtonNext' at Center.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.ButtonNextInfo, new RecordItemIndex(6));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.ButtonNext.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
