///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using DashboardLibrary;
namespace DashboardLibrary.ActionsDataProfile
{
    public partial class CreateSortField
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SelectAndAddLevel(RepoItemInfo selecttagInfo, RepoItemInfo inputtagInfo,String varListOption)
        {
        	String[] lstOption= null;
        	Report.Info(varListOption);
        	if(varListOption.Contains(","))
        	{
        		lstOption= varListOption.Split(',');
        	}
        	else
        	{
        		lstOption = new string[1]{varListOption};
        	}
        	
        	
        	for(int i =0;i<lstOption.Length;i++)
        	{
        		Report.Info(lstOption[i]);
								
				Report.Log(ReportLevel.Info, "Select", "SetValue item .", selecttagInfo);
				selecttagInfo.FindAdapter<SelectTag>().TagValue=lstOption[i];
				
            	Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'inputtagInfo' at Center.", inputtagInfo);
            	inputtagInfo.FindAdapter<InputTag>().Click();
        	}
        }
    }
}
