///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsDataProfile
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteDataProfile recording.
    /// </summary>
    [TestModule("de9b8bc5-25a9-420c-b320-53475ad616a3", ModuleType.Recording, 1)]
    public partial class DeleteDataProfile : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static DeleteDataProfile instance = new DeleteDataProfile();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteDataProfile()
        {
            varItemDataProfile = "";
            varName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteDataProfile Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varItemDataProfile.
        /// </summary>
        [TestVariable("bc8c09dc-2fd8-41ac-ab34-74bc09534c66")]
        public string varItemDataProfile
        {
            get { return repo.varItemDataProfile; }
            set { repo.varItemDataProfile = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varName.
        /// </summary>
        [TestVariable("5dbaf6f7-ae32-43af-9c0b-f371c9329137")]
        public string varName
        {
            get { return repo.varName; }
            set { repo.varName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            varItemDataProfile = UserCodeUtilities.updateName(varItemDataProfile);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.DeleteItemDataProfile' at Center.", repo.TestArchitect.ActionsDataProfile.DeleteItemDataProfileInfo, new RecordItemIndex(1));
            repo.TestArchitect.ActionsDataProfile.DeleteItemDataProfile.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
