///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsDataProfile
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditGeneralSetting recording.
    /// </summary>
    [TestModule("ae6a36a7-8184-496b-998c-4a85e9e4a343", ModuleType.Recording, 1)]
    public partial class EditGeneralSetting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static EditGeneralSetting instance = new EditGeneralSetting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditGeneralSetting()
        {
            varItemDataProfile = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditGeneralSetting Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varItemDataProfile.
        /// </summary>
        [TestVariable("bc8c09dc-2fd8-41ac-ab34-74bc09534c66")]
        public string varItemDataProfile
        {
            get { return repo.varItemDataProfile; }
            set { repo.varItemDataProfile = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.EditDataProfile' at Center.", repo.TestArchitect.ActionsDataProfile.EditDataProfileInfo, new RecordItemIndex(0));
            repo.TestArchitect.ActionsDataProfile.EditDataProfile.Click();
            Delay.Milliseconds(0);
            
            varItemDataProfile = UserCodeUtilities.updateName(varItemDataProfile);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$varItemDataProfile' on item 'TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName'.", repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileNameInfo, new RecordItemIndex(2));
            repo.TestArchitect.ActionsDataProfile.CreateGeneralSettings.TxtProfileName.Element.SetAttributeValue("Value", varItemDataProfile);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.ButtonProfileSetting' at Center.", repo.TestArchitect.ActionsDataProfile.ButtonProfileSettingInfo, new RecordItemIndex(3));
            repo.TestArchitect.ActionsDataProfile.ButtonProfileSetting.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsDataProfile.ItemDataProfile' at Center.", repo.TestArchitect.ActionsDataProfile.ItemDataProfileInfo, new RecordItemIndex(4));
            repo.TestArchitect.ActionsDataProfile.ItemDataProfile.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
