///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DashboardLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DashboardLibraryRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b7ff0fae-7b8d-4910-97af-49ef286a1d67")]
    public partial class DashboardLibraryRepository : RepoGenBaseFolder
    {
        static DashboardLibraryRepository instance = new DashboardLibraryRepository();
        DashboardLibraryRepositoryFolders.TestArchitectAppFolder _testarchitect;
        DashboardLibraryRepositoryFolders.MessageFromWebpageAppFolder _messagefromwebpage;
        DashboardLibraryRepositoryFolders.ChromeppAppFolder _chromepp;

        /// <summary>
        /// Gets the singleton class instance representing the DashboardLibraryRepository element repository.
        /// </summary>
        [RepositoryFolder("b7ff0fae-7b8d-4910-97af-49ef286a1d67")]
        public static DashboardLibraryRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DashboardLibraryRepository() 
            : base("DashboardLibraryRepository", "/", null, 0, false, "b7ff0fae-7b8d-4910-97af-49ef286a1d67", ".\\RepositoryImages\\DashboardLibraryRepositoryb7ff0fae.rximgres")
        {
            _testarchitect = new DashboardLibraryRepositoryFolders.TestArchitectAppFolder(this);
            _messagefromwebpage = new DashboardLibraryRepositoryFolders.MessageFromWebpageAppFolder(this);
            _chromepp = new DashboardLibraryRepositoryFolders.ChromeppAppFolder(this);
        }

#region Variables

        string _var = "";

        /// <summary>
        /// Gets or sets the value of variable var.
        /// </summary>
        [TestVariable("352a4512-098d-4a2b-a20c-1796ea086442")]
        public string var
        {
            get { return _var; }
            set { _var = value; }
        }

        string _varName = "";

        /// <summary>
        /// Gets or sets the value of variable varName.
        /// </summary>
        [TestVariable("b1b90102-b72f-4f41-a881-59557ee6a285")]
        public string varName
        {
            get { return _varName; }
            set { _varName = value; }
        }

        string _varItem = "";

        /// <summary>
        /// Gets or sets the value of variable varItem.
        /// </summary>
        [TestVariable("739d76eb-a7ae-4c24-ad1f-6296c5052bed")]
        public string varItem
        {
            get { return _varItem; }
            set { _varItem = value; }
        }

        string _varItemReport = "";

        /// <summary>
        /// Gets or sets the value of variable varItemReport.
        /// </summary>
        [TestVariable("ba525e2f-cd9e-47c9-a2f6-d8ed1546f584")]
        public string varItemReport
        {
            get { return _varItemReport; }
            set { _varItemReport = value; }
        }

        string _varItemType = "";

        /// <summary>
        /// Gets or sets the value of variable varItemType.
        /// </summary>
        [TestVariable("011758ba-82f4-430f-9f38-df0b41527783")]
        public string varItemType
        {
            get { return _varItemType; }
            set { _varItemType = value; }
        }

        string _varItemField = "";

        /// <summary>
        /// Gets or sets the value of variable varItemField.
        /// </summary>
        [TestVariable("50d431d7-30c0-49d4-8526-80fca15b0a59")]
        public string varItemField
        {
            get { return _varItemField; }
            set { _varItemField = value; }
        }

        string _varItemDataProfile = "";

        /// <summary>
        /// Gets or sets the value of variable varItemDataProfile.
        /// </summary>
        [TestVariable("bc8c09dc-2fd8-41ac-ab34-74bc09534c66")]
        public string varItemDataProfile
        {
            get { return _varItemDataProfile; }
            set { _varItemDataProfile = value; }
        }

        string _varItemFielded = "";

        /// <summary>
        /// Gets or sets the value of variable varItemFielded.
        /// </summary>
        [TestVariable("9c6a7041-c892-4893-a933-71a344467922")]
        public string varItemFielded
        {
            get { return _varItemFielded; }
            set { _varItemFielded = value; }
        }

        string _varColor = "";

        /// <summary>
        /// Gets or sets the value of variable varColor.
        /// </summary>
        [TestVariable("9ba4778d-f504-4314-87cb-4cb9d050a92b")]
        public string varColor
        {
            get { return _varColor; }
            set { _varColor = value; }
        }

        string _varNumber = "";

        /// <summary>
        /// Gets or sets the value of variable varNumber.
        /// </summary>
        [TestVariable("bed04538-02d3-4668-b23f-49c379f09b92")]
        public string varNumber
        {
            get { return _varNumber; }
            set { _varNumber = value; }
        }

        string _varDisplayName = "";

        /// <summary>
        /// Gets or sets the value of variable varDisplayName.
        /// </summary>
        [TestVariable("b472c6fe-35b8-408a-b3c2-4ec395edcf46")]
        public string varDisplayName
        {
            get { return _varDisplayName; }
            set { _varDisplayName = value; }
        }

        string _varData = "";

        /// <summary>
        /// Gets or sets the value of variable varData.
        /// </summary>
        [TestVariable("4f0da9e7-9be5-4630-bac2-8de3bc3a7466")]
        public string varData
        {
            get { return _varData; }
            set { _varData = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b7ff0fae-7b8d-4910-97af-49ef286a1d67")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TestArchitect folder.
        /// </summary>
        [RepositoryFolder("10abeb5d-342a-48a2-a14d-cf59e28f8c01")]
        public virtual DashboardLibraryRepositoryFolders.TestArchitectAppFolder TestArchitect
        {
            get { return _testarchitect; }
        }

        /// <summary>
        /// The MessageFromWebpage folder.
        /// </summary>
        [RepositoryFolder("a89b6eed-e0ff-4f7b-a5ab-2fb683644fd2")]
        public virtual DashboardLibraryRepositoryFolders.MessageFromWebpageAppFolder MessageFromWebpage
        {
            get { return _messagefromwebpage; }
        }

        /// <summary>
        /// The chromepp folder.
        /// </summary>
        [RepositoryFolder("7a172279-4e8e-493e-bb85-db8abb3a46e0")]
        public virtual DashboardLibraryRepositoryFolders.ChromeppAppFolder chromepp
        {
            get { return _chromepp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class DashboardLibraryRepositoryFolders
    {
        /// <summary>
        /// The TestArchitectAppFolder folder.
        /// </summary>
        [RepositoryFolder("10abeb5d-342a-48a2-a14d-cf59e28f8c01")]
        public partial class TestArchitectAppFolder : RepoGenBaseFolder
        {
            DashboardLibraryRepositoryFolders.LoginDashboardFolder _logindashboard;
            DashboardLibraryRepositoryFolders.AdministersFolder _administers;
            DashboardLibraryRepositoryFolders.ActionsPageFolder _actionspage;
            DashboardLibraryRepositoryFolders.ActionsDataProfileFolder _actionsdataprofile;
            DashboardLibraryRepositoryFolders.ActionsPanelsFolder _actionspanels;
            RepoItemInfo _globalsettingInfo;
            RepoItemInfo _pagenameInfo;
            RepoItemInfo _pageokInfo;
            RepoItemInfo _administratorInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _testpagetabInfo;

            /// <summary>
            /// Creates a new TestArchitect  folder.
            /// </summary>
            public TestArchitectAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestArchitect", "/dom[@domain='localhost']", parentFolder, 30000, null, false, "10abeb5d-342a-48a2-a14d-cf59e28f8c01", "")
            {
                _logindashboard = new DashboardLibraryRepositoryFolders.LoginDashboardFolder(this);
                _administers = new DashboardLibraryRepositoryFolders.AdministersFolder(this);
                _actionspage = new DashboardLibraryRepositoryFolders.ActionsPageFolder(this);
                _actionsdataprofile = new DashboardLibraryRepositoryFolders.ActionsDataProfileFolder(this);
                _actionspanels = new DashboardLibraryRepositoryFolders.ActionsPanelsFolder(this);
                _globalsettingInfo = new RepoItemInfo(this, "GlobalSetting", ".//div[#'main-menu']//ul/li[@safeclass='mn-setting']", 30000, null, "d7344714-fb0c-48ef-96ec-205a8fab2b34");
                _pagenameInfo = new RepoItemInfo(this, "PageName", ".//input[#'name']", 30000, null, "6e6fad88-5dfc-4a26-9cb2-f928825cb2fb");
                _pageokInfo = new RepoItemInfo(this, "PageOK", ".//input[#'OK']", 30000, null, "a03c0468-31b2-42df-a78c-c63d933c1b35");
                _administratorInfo = new RepoItemInfo(this, "Administrator", ".//div[#'header']//ul//a[@innertext='administrator']", 30000, null, "cd63fbe8-7f51-4a5c-8997-088e77295cde");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//div[#'header']//ul/li[5]/ul//a[@innertext='Logout']", 30000, null, "3c42aec0-62cd-4f87-bc0c-7d87ba90ccae");
                _testpagetabInfo = new RepoItemInfo(this, "TestPageTab", ".//div[#'main-menu']//ul//a[@innertext=$varName]", 30000, null, "1264fad8-54dd-4bde-aa15-94fb5d37af57");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10abeb5d-342a-48a2-a14d-cf59e28f8c01")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10abeb5d-342a-48a2-a14d-cf59e28f8c01")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GlobalSetting item.
            /// </summary>
            [RepositoryItem("d7344714-fb0c-48ef-96ec-205a8fab2b34")]
            public virtual Ranorex.LiTag GlobalSetting
            {
                get
                {
                    return _globalsettingInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The GlobalSetting item info.
            /// </summary>
            [RepositoryItemInfo("d7344714-fb0c-48ef-96ec-205a8fab2b34")]
            public virtual RepoItemInfo GlobalSettingInfo
            {
                get
                {
                    return _globalsettingInfo;
                }
            }

            /// <summary>
            /// The PageName item.
            /// </summary>
            [RepositoryItem("6e6fad88-5dfc-4a26-9cb2-f928825cb2fb")]
            public virtual Ranorex.InputTag PageName
            {
                get
                {
                    return _pagenameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PageName item info.
            /// </summary>
            [RepositoryItemInfo("6e6fad88-5dfc-4a26-9cb2-f928825cb2fb")]
            public virtual RepoItemInfo PageNameInfo
            {
                get
                {
                    return _pagenameInfo;
                }
            }

            /// <summary>
            /// The PageOK item.
            /// </summary>
            [RepositoryItem("a03c0468-31b2-42df-a78c-c63d933c1b35")]
            public virtual Ranorex.InputTag PageOK
            {
                get
                {
                    return _pageokInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PageOK item info.
            /// </summary>
            [RepositoryItemInfo("a03c0468-31b2-42df-a78c-c63d933c1b35")]
            public virtual RepoItemInfo PageOKInfo
            {
                get
                {
                    return _pageokInfo;
                }
            }

            /// <summary>
            /// The Administrator item.
            /// </summary>
            [RepositoryItem("cd63fbe8-7f51-4a5c-8997-088e77295cde")]
            public virtual Ranorex.ATag Administrator
            {
                get
                {
                    return _administratorInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Administrator item info.
            /// </summary>
            [RepositoryItemInfo("cd63fbe8-7f51-4a5c-8997-088e77295cde")]
            public virtual RepoItemInfo AdministratorInfo
            {
                get
                {
                    return _administratorInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("3c42aec0-62cd-4f87-bc0c-7d87ba90ccae")]
            public virtual Ranorex.ATag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("3c42aec0-62cd-4f87-bc0c-7d87ba90ccae")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The TestPageTab item.
            /// </summary>
            [RepositoryItem("1264fad8-54dd-4bde-aa15-94fb5d37af57")]
            public virtual Ranorex.ATag TestPageTab
            {
                get
                {
                    return _testpagetabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TestPageTab item info.
            /// </summary>
            [RepositoryItemInfo("1264fad8-54dd-4bde-aa15-94fb5d37af57")]
            public virtual RepoItemInfo TestPageTabInfo
            {
                get
                {
                    return _testpagetabInfo;
                }
            }

            /// <summary>
            /// The loginDashboard folder.
            /// </summary>
            [RepositoryFolder("b6ae025d-210d-415a-b3dc-e58bbad4671f")]
            public virtual DashboardLibraryRepositoryFolders.LoginDashboardFolder loginDashboard
            {
                get { return _logindashboard; }
            }

            /// <summary>
            /// The Administers folder.
            /// </summary>
            [RepositoryFolder("fbfdc009-6cc6-498b-97a7-a490009f8c0b")]
            public virtual DashboardLibraryRepositoryFolders.AdministersFolder Administers
            {
                get { return _administers; }
            }

            /// <summary>
            /// The ActionsPage folder.
            /// </summary>
            [RepositoryFolder("c736c4a9-1956-4834-b88d-d4fc24c9537b")]
            public virtual DashboardLibraryRepositoryFolders.ActionsPageFolder ActionsPage
            {
                get { return _actionspage; }
            }

            /// <summary>
            /// The ActionsDataProfile folder.
            /// </summary>
            [RepositoryFolder("ee0dd93a-76c7-4a64-82b1-db70577821e8")]
            public virtual DashboardLibraryRepositoryFolders.ActionsDataProfileFolder ActionsDataProfile
            {
                get { return _actionsdataprofile; }
            }

            /// <summary>
            /// The ActionsPanels folder.
            /// </summary>
            [RepositoryFolder("d4660e83-bf23-417c-a9b1-47d6d3e8addb")]
            public virtual DashboardLibraryRepositoryFolders.ActionsPanelsFolder ActionsPanels
            {
                get { return _actionspanels; }
            }
        }

        /// <summary>
        /// The LoginDashboardFolder folder.
        /// </summary>
        [RepositoryFolder("b6ae025d-210d-415a-b3dc-e58bbad4671f")]
        public partial class LoginDashboardFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new loginDashboard  folder.
            /// </summary>
            public LoginDashboardFolder(RepoGenBaseFolder parentFolder) :
                    base("loginDashboard", "", parentFolder, 0, null, false, "b6ae025d-210d-415a-b3dc-e58bbad4671f", "")
            {
                _usernameInfo = new RepoItemInfo(this, "Username", ".//input[#'username']", 30000, null, "8f98ae6a-c1df-4318-a710-184d4c1baa96");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "b724b041-4db1-4c72-85e4-ddc438e23b83");
                _loginInfo = new RepoItemInfo(this, "Login", ".//div[#'content']/div/div[@innertext='Login' and @safeclass='btn-login']", 30000, null, "22e47d28-c514-4df7-a3bd-f4da96932742");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b6ae025d-210d-415a-b3dc-e58bbad4671f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("8f98ae6a-c1df-4318-a710-184d4c1baa96")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("8f98ae6a-c1df-4318-a710-184d4c1baa96")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("b724b041-4db1-4c72-85e4-ddc438e23b83")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("b724b041-4db1-4c72-85e4-ddc438e23b83")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("22e47d28-c514-4df7-a3bd-f4da96932742")]
            public virtual Ranorex.DivTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("22e47d28-c514-4df7-a3bd-f4da96932742")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The AdministersFolder folder.
        /// </summary>
        [RepositoryFolder("fbfdc009-6cc6-498b-97a7-a490009f8c0b")]
        public partial class AdministersFolder : RepoGenBaseFolder
        {
            RepoItemInfo _administerInfo;
            RepoItemInfo _dataprofilesInfo;
            RepoItemInfo _panelsInfo;
            RepoItemInfo _addnewInfo;
            RepoItemInfo _deleteallitemsInfo;

            /// <summary>
            /// Creates a new Administers  folder.
            /// </summary>
            public AdministersFolder(RepoGenBaseFolder parentFolder) :
                    base("Administers", "", parentFolder, 0, null, false, "fbfdc009-6cc6-498b-97a7-a490009f8c0b", "")
            {
                _administerInfo = new RepoItemInfo(this, "Administer", ".//div[#'header']//ul//a[@innertext='Administer']", 30000, null, "4bdeae27-f280-4598-b859-412084e8392e");
                _dataprofilesInfo = new RepoItemInfo(this, "DataProfiles", ".//ul[#'ulAdminister']//a[@innertext='Data Profiles']", 30000, null, "2e2c0346-094b-402e-bbc6-40724290aa8b");
                _panelsInfo = new RepoItemInfo(this, "Panels", ".//ul[#'ulAdminister']//a[@innertext='Panels']", 30000, null, "fa5bc057-2131-49e0-abcc-9845205214aa");
                _addnewInfo = new RepoItemInfo(this, "AddNew", ".//form[#'form1']//a[@innertext='Add New']", 30000, null, "0d3f8ed5-9142-49be-95b9-08bd881e4314");
                _deleteallitemsInfo = new RepoItemInfo(this, "DeleteAllItems", ".//form[#'form1']//a[@innertext='Delete']", 30000, null, "c8b718d6-dd41-4e13-b1ad-a02e39ba2664");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fbfdc009-6cc6-498b-97a7-a490009f8c0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Administer item.
            /// </summary>
            [RepositoryItem("4bdeae27-f280-4598-b859-412084e8392e")]
            public virtual Ranorex.ATag Administer
            {
                get
                {
                    return _administerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Administer item info.
            /// </summary>
            [RepositoryItemInfo("4bdeae27-f280-4598-b859-412084e8392e")]
            public virtual RepoItemInfo AdministerInfo
            {
                get
                {
                    return _administerInfo;
                }
            }

            /// <summary>
            /// The DataProfiles item.
            /// </summary>
            [RepositoryItem("2e2c0346-094b-402e-bbc6-40724290aa8b")]
            public virtual Ranorex.ATag DataProfiles
            {
                get
                {
                    return _dataprofilesInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DataProfiles item info.
            /// </summary>
            [RepositoryItemInfo("2e2c0346-094b-402e-bbc6-40724290aa8b")]
            public virtual RepoItemInfo DataProfilesInfo
            {
                get
                {
                    return _dataprofilesInfo;
                }
            }

            /// <summary>
            /// The Panels item.
            /// </summary>
            [RepositoryItem("fa5bc057-2131-49e0-abcc-9845205214aa")]
            public virtual Ranorex.ATag Panels
            {
                get
                {
                    return _panelsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Panels item info.
            /// </summary>
            [RepositoryItemInfo("fa5bc057-2131-49e0-abcc-9845205214aa")]
            public virtual RepoItemInfo PanelsInfo
            {
                get
                {
                    return _panelsInfo;
                }
            }

            /// <summary>
            /// The AddNew item.
            /// </summary>
            [RepositoryItem("0d3f8ed5-9142-49be-95b9-08bd881e4314")]
            public virtual Ranorex.ATag AddNew
            {
                get
                {
                    return _addnewInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddNew item info.
            /// </summary>
            [RepositoryItemInfo("0d3f8ed5-9142-49be-95b9-08bd881e4314")]
            public virtual RepoItemInfo AddNewInfo
            {
                get
                {
                    return _addnewInfo;
                }
            }

            /// <summary>
            /// The DeleteAllItems item.
            /// </summary>
            [RepositoryItem("c8b718d6-dd41-4e13-b1ad-a02e39ba2664")]
            public virtual Ranorex.ATag DeleteAllItems
            {
                get
                {
                    return _deleteallitemsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DeleteAllItems item info.
            /// </summary>
            [RepositoryItemInfo("c8b718d6-dd41-4e13-b1ad-a02e39ba2664")]
            public virtual RepoItemInfo DeleteAllItemsInfo
            {
                get
                {
                    return _deleteallitemsInfo;
                }
            }
        }

        /// <summary>
        /// The ActionsPageFolder folder.
        /// </summary>
        [RepositoryFolder("c736c4a9-1956-4834-b88d-d4fc24c9537b")]
        public partial class ActionsPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addpageInfo;
            RepoItemInfo _editpageInfo;
            RepoItemInfo _deletepageInfo;

            /// <summary>
            /// Creates a new ActionsPage  folder.
            /// </summary>
            public ActionsPageFolder(RepoGenBaseFolder parentFolder) :
                    base("ActionsPage", "", parentFolder, 0, null, false, "c736c4a9-1956-4834-b88d-d4fc24c9537b", "")
            {
                _addpageInfo = new RepoItemInfo(this, "AddPage", ".//div[#'main-menu']//a[@innertext='Add Page']", 30000, null, "ecbdd83f-c6a2-483c-98fd-9efb93530af8");
                _editpageInfo = new RepoItemInfo(this, "EditPage", ".//div[#'main-menu']//ul//ul//a[@innertext='Edit']", 30000, null, "31979903-baa3-4a20-bde5-a96e50908354");
                _deletepageInfo = new RepoItemInfo(this, "DeletePage", ".//div[#'main-menu']//ul//ul//a[@innertext='Delete']", 30000, null, "389bdd25-9b3b-453e-b195-d98c8168cb62");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c736c4a9-1956-4834-b88d-d4fc24c9537b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddPage item.
            /// </summary>
            [RepositoryItem("ecbdd83f-c6a2-483c-98fd-9efb93530af8")]
            public virtual Ranorex.ATag AddPage
            {
                get
                {
                    return _addpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AddPage item info.
            /// </summary>
            [RepositoryItemInfo("ecbdd83f-c6a2-483c-98fd-9efb93530af8")]
            public virtual RepoItemInfo AddPageInfo
            {
                get
                {
                    return _addpageInfo;
                }
            }

            /// <summary>
            /// The EditPage item.
            /// </summary>
            [RepositoryItem("31979903-baa3-4a20-bde5-a96e50908354")]
            public virtual Ranorex.ATag EditPage
            {
                get
                {
                    return _editpageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditPage item info.
            /// </summary>
            [RepositoryItemInfo("31979903-baa3-4a20-bde5-a96e50908354")]
            public virtual RepoItemInfo EditPageInfo
            {
                get
                {
                    return _editpageInfo;
                }
            }

            /// <summary>
            /// The DeletePage item.
            /// </summary>
            [RepositoryItem("389bdd25-9b3b-453e-b195-d98c8168cb62")]
            public virtual Ranorex.ATag DeletePage
            {
                get
                {
                    return _deletepageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DeletePage item info.
            /// </summary>
            [RepositoryItemInfo("389bdd25-9b3b-453e-b195-d98c8168cb62")]
            public virtual RepoItemInfo DeletePageInfo
            {
                get
                {
                    return _deletepageInfo;
                }
            }
        }

        /// <summary>
        /// The ActionsDataProfileFolder folder.
        /// </summary>
        [RepositoryFolder("ee0dd93a-76c7-4a64-82b1-db70577821e8")]
        public partial class ActionsDataProfileFolder : RepoGenBaseFolder
        {
            DashboardLibraryRepositoryFolders.CreateGeneralSettingsFolder _creategeneralsettings;
            DashboardLibraryRepositoryFolders.DislayFieldFolder _dislayfield;
            DashboardLibraryRepositoryFolders.SortFieldFolder _sortfield;
            RepoItemInfo _editdataprofileInfo;
            RepoItemInfo _itemdataprofileInfo;
            RepoItemInfo _editdataprofilechromeInfo;
            RepoItemInfo _buttonprofilesettingInfo;
            RepoItemInfo _deleteitemdataprofileInfo;

            /// <summary>
            /// Creates a new ActionsDataProfile  folder.
            /// </summary>
            public ActionsDataProfileFolder(RepoGenBaseFolder parentFolder) :
                    base("ActionsDataProfile", "", parentFolder, 0, null, false, "ee0dd93a-76c7-4a64-82b1-db70577821e8", "")
            {
                _creategeneralsettings = new DashboardLibraryRepositoryFolders.CreateGeneralSettingsFolder(this);
                _dislayfield = new DashboardLibraryRepositoryFolders.DislayFieldFolder(this);
                _sortfield = new DashboardLibraryRepositoryFolders.SortFieldFolder(this);
                _editdataprofileInfo = new RepoItemInfo(this, "EditDataProfile", ".//form[#'form1']//table/tbody/tr/td/a[@innertext=$varItemDataProfile]//parent::td/following-sibling::td[7]/a[@innertext='Edit']", 30000, null, "0fcf3e3e-8ddd-453a-9869-7fc612ccec59");
                _itemdataprofileInfo = new RepoItemInfo(this, "ItemDataProfile", ".//form[#'form1']//table/tbody///a[@innertext=$varItemDataProfile]", 30000, null, "3b7265bb-7f94-4bd1-ac63-d6dd332628a2");
                _editdataprofilechromeInfo = new RepoItemInfo(this, "EditDataProfileChrome", ".//form[#'form1']//table/tbody//tr/td[text()=$varItemDataProfile]/following-sibling::td[7]/a[@innertext='Edit']", 30000, null, "d5b8e21d-80f6-43b5-8e2e-0406292cccc6");
                _buttonprofilesettingInfo = new RepoItemInfo(this, "ButtonProfileSetting", ".//table[#'profilesettingsdetail']//input[@value='Finish']", 30000, null, "7006680b-6ca2-41b0-99c4-71cde4cd3655");
                _deleteitemdataprofileInfo = new RepoItemInfo(this, "DeleteItemDataProfile", ".//form[#'form1']//table/tbody/tr/td/a[@innertext=$varItemDataProfile]//parent::td/following-sibling::td[7]/a[@innertext='Delete']", 30000, null, "44db8363-7597-4f94-8544-ef4080fd66fa");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee0dd93a-76c7-4a64-82b1-db70577821e8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EditDataProfile item.
            /// </summary>
            [RepositoryItem("0fcf3e3e-8ddd-453a-9869-7fc612ccec59")]
            public virtual Ranorex.ATag EditDataProfile
            {
                get
                {
                    return _editdataprofileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditDataProfile item info.
            /// </summary>
            [RepositoryItemInfo("0fcf3e3e-8ddd-453a-9869-7fc612ccec59")]
            public virtual RepoItemInfo EditDataProfileInfo
            {
                get
                {
                    return _editdataprofileInfo;
                }
            }

            /// <summary>
            /// The ItemDataProfile item.
            /// </summary>
            [RepositoryItem("3b7265bb-7f94-4bd1-ac63-d6dd332628a2")]
            public virtual Ranorex.ATag ItemDataProfile
            {
                get
                {
                    return _itemdataprofileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ItemDataProfile item info.
            /// </summary>
            [RepositoryItemInfo("3b7265bb-7f94-4bd1-ac63-d6dd332628a2")]
            public virtual RepoItemInfo ItemDataProfileInfo
            {
                get
                {
                    return _itemdataprofileInfo;
                }
            }

            /// <summary>
            /// The EditDataProfileChrome item.
            /// </summary>
            [RepositoryItem("d5b8e21d-80f6-43b5-8e2e-0406292cccc6")]
            public virtual Ranorex.ATag EditDataProfileChrome
            {
                get
                {
                    return _editdataprofilechromeInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditDataProfileChrome item info.
            /// </summary>
            [RepositoryItemInfo("d5b8e21d-80f6-43b5-8e2e-0406292cccc6")]
            public virtual RepoItemInfo EditDataProfileChromeInfo
            {
                get
                {
                    return _editdataprofilechromeInfo;
                }
            }

            /// <summary>
            /// The ButtonProfileSetting item.
            /// </summary>
            [RepositoryItem("7006680b-6ca2-41b0-99c4-71cde4cd3655")]
            public virtual Ranorex.InputTag ButtonProfileSetting
            {
                get
                {
                    return _buttonprofilesettingInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ButtonProfileSetting item info.
            /// </summary>
            [RepositoryItemInfo("7006680b-6ca2-41b0-99c4-71cde4cd3655")]
            public virtual RepoItemInfo ButtonProfileSettingInfo
            {
                get
                {
                    return _buttonprofilesettingInfo;
                }
            }

            /// <summary>
            /// The DeleteItemDataProfile item.
            /// </summary>
            [RepositoryItem("44db8363-7597-4f94-8544-ef4080fd66fa")]
            public virtual Ranorex.ATag DeleteItemDataProfile
            {
                get
                {
                    return _deleteitemdataprofileInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DeleteItemDataProfile item info.
            /// </summary>
            [RepositoryItemInfo("44db8363-7597-4f94-8544-ef4080fd66fa")]
            public virtual RepoItemInfo DeleteItemDataProfileInfo
            {
                get
                {
                    return _deleteitemdataprofileInfo;
                }
            }

            /// <summary>
            /// The CreateGeneralSettings folder.
            /// </summary>
            [RepositoryFolder("9beb0163-89c3-4d46-be06-eb1aef738d5a")]
            public virtual DashboardLibraryRepositoryFolders.CreateGeneralSettingsFolder CreateGeneralSettings
            {
                get { return _creategeneralsettings; }
            }

            /// <summary>
            /// The DislayField folder.
            /// </summary>
            [RepositoryFolder("fc22f2da-5b10-4547-ac5e-7154d4d27762")]
            public virtual DashboardLibraryRepositoryFolders.DislayFieldFolder DislayField
            {
                get { return _dislayfield; }
            }

            /// <summary>
            /// The SortField folder.
            /// </summary>
            [RepositoryFolder("1e482995-a86b-4280-af74-67db3dd98932")]
            public virtual DashboardLibraryRepositoryFolders.SortFieldFolder SortField
            {
                get { return _sortfield; }
            }
        }

        /// <summary>
        /// The CreateGeneralSettingsFolder folder.
        /// </summary>
        [RepositoryFolder("9beb0163-89c3-4d46-be06-eb1aef738d5a")]
        public partial class CreateGeneralSettingsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _chkdistinctInfo;
            CbbSubReportInfoClass _cbbsubreportInfo;
            CbbItemTypeInfoClass _cbbitemtypeInfo;
            RepoItemInfo _txtprofilenameInfo;
            RepoItemInfo _buttonnextInfo;

            /// <summary>
            /// Creates a new CreateGeneralSettings  folder.
            /// </summary>
            public CreateGeneralSettingsFolder(RepoGenBaseFolder parentFolder) :
                    base("CreateGeneralSettings", "", parentFolder, 0, null, false, "9beb0163-89c3-4d46-be06-eb1aef738d5a", "")
            {
                _chkdistinctInfo = new RepoItemInfo(this, "ChkDistinct", ".//input[#'chkDistinct']", 30000, null, "bad72527-e74d-45da-9f6d-af6919d6defa");
                _cbbsubreportInfo = new CbbSubReportInfoClass(this);
                _cbbitemtypeInfo = new CbbItemTypeInfoClass(this);
                _txtprofilenameInfo = new RepoItemInfo(this, "TxtProfileName", ".//input[#'txtProfileName']", 30000, null, "835f948e-b4f1-4107-bd05-d5c4f244787f");
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", ".//table[#'profilesettingsdetail']/tbody/tr[5]/?/?/input[@value='Next']", 30000, null, "ad9dc90d-0be4-4827-a48d-50214f29133a");
            }

            /// <summary>
            /// The CbbSubReportInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("79a67b4b-93cc-43ee-803c-db25b40962bb")]
            public class CbbSubReportInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CbbSubReportInfoClass class constructor.
                /// </summary>
                public CbbSubReportInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CbbSubReport", ".//select[#'cbbSubReport']", 30000, null, "79a67b4b-93cc-43ee-803c-db25b40962bb")
                { }

                /// <summary>
                /// Gets the Related_Test_Result item image.
                /// </summary>
                /// <returns>The Related_Test_Result image.</returns>
                [RepositoryImage("955c98ef-0502-4ecb-9892-6d4c79f55803")]
                public CompressedImage GetRelated_Test_Result()
                {
                    return GetImage("955c98ef-0502-4ecb-9892-6d4c79f55803");
                }

                /// <summary>
                /// Gets the Related_Test_Result item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("955c98ef-0502-4ecb-9892-6d4c79f55803")]
                public CompressedImage GetRelated_Test_Result(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("955c98ef-0502-4ecb-9892-6d4c79f55803", cropRect);
                }
            }

            /// <summary>
            /// The CbbItemTypeInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("0884108e-0f34-4141-9608-eecfb786e884")]
            public class CbbItemTypeInfoClass : RepoItemInfo
            {
                /// <summary>
                /// CbbItemTypeInfoClass class constructor.
                /// </summary>
                public CbbItemTypeInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "CbbItemType", ".//select[#'cbbEntityType']", 30000, null, "0884108e-0f34-4141-9608-eecfb786e884")
                { }

                /// <summary>
                /// Gets the TestModules item image.
                /// </summary>
                /// <returns>The TestModules image.</returns>
                [RepositoryImage("e0e60877-d5bc-4dc2-acd7-ba1cd312dc3f")]
                public CompressedImage GetTestModules()
                {
                    return GetImage("e0e60877-d5bc-4dc2-acd7-ba1cd312dc3f");
                }

                /// <summary>
                /// Gets the TestModules item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e0e60877-d5bc-4dc2-acd7-ba1cd312dc3f")]
                public CompressedImage GetTestModules(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e0e60877-d5bc-4dc2-acd7-ba1cd312dc3f", cropRect);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9beb0163-89c3-4d46-be06-eb1aef738d5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ChkDistinct item.
            /// </summary>
            [RepositoryItem("bad72527-e74d-45da-9f6d-af6919d6defa")]
            public virtual Ranorex.InputTag ChkDistinct
            {
                get
                {
                    return _chkdistinctInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkDistinct item info.
            /// </summary>
            [RepositoryItemInfo("bad72527-e74d-45da-9f6d-af6919d6defa")]
            public virtual RepoItemInfo ChkDistinctInfo
            {
                get
                {
                    return _chkdistinctInfo;
                }
            }

            /// <summary>
            /// The CbbSubReport item.
            /// </summary>
            [RepositoryItem("79a67b4b-93cc-43ee-803c-db25b40962bb")]
            public virtual Ranorex.SelectTag CbbSubReport
            {
                get
                {
                    return _cbbsubreportInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbSubReport item info.
            /// </summary>
            [RepositoryItemInfo("79a67b4b-93cc-43ee-803c-db25b40962bb")]
            public virtual CbbSubReportInfoClass CbbSubReportInfo
            {
                get
                {
                    return _cbbsubreportInfo;
                }
            }

            /// <summary>
            /// The CbbItemType item.
            /// </summary>
            [RepositoryItem("0884108e-0f34-4141-9608-eecfb786e884")]
            public virtual Ranorex.SelectTag CbbItemType
            {
                get
                {
                    return _cbbitemtypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbItemType item info.
            /// </summary>
            [RepositoryItemInfo("0884108e-0f34-4141-9608-eecfb786e884")]
            public virtual CbbItemTypeInfoClass CbbItemTypeInfo
            {
                get
                {
                    return _cbbitemtypeInfo;
                }
            }

            /// <summary>
            /// The TxtProfileName item.
            /// </summary>
            [RepositoryItem("835f948e-b4f1-4107-bd05-d5c4f244787f")]
            public virtual Ranorex.InputTag TxtProfileName
            {
                get
                {
                    return _txtprofilenameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtProfileName item info.
            /// </summary>
            [RepositoryItemInfo("835f948e-b4f1-4107-bd05-d5c4f244787f")]
            public virtual RepoItemInfo TxtProfileNameInfo
            {
                get
                {
                    return _txtprofilenameInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("ad9dc90d-0be4-4827-a48d-50214f29133a")]
            public virtual Ranorex.InputTag ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("ad9dc90d-0be4-4827-a48d-50214f29133a")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }
        }

        /// <summary>
        /// The DislayFieldFolder folder.
        /// </summary>
        [RepositoryFolder("fc22f2da-5b10-4547-ac5e-7154d4d27762")]
        public partial class DislayFieldFolder : RepoGenBaseFolder
        {
            RepoItemInfo _displayfieldsInfo;
            RepoItemInfo _chkdescriptionInfo;
            RepoItemInfo _chknameInfo;
            RepoItemInfo _chksourceInfo;
            RepoItemInfo _chkassignedInfo;
            RepoItemInfo _chkstatusInfo;
            RepoItemInfo _chknotesInfo;
            RepoItemInfo _chkurlInfo;
            RepoItemInfo _buttonnextfieldInfo;

            /// <summary>
            /// Creates a new DislayField  folder.
            /// </summary>
            public DislayFieldFolder(RepoGenBaseFolder parentFolder) :
                    base("DislayField", "", parentFolder, 0, null, false, "fc22f2da-5b10-4547-ac5e-7154d4d27762", "")
            {
                _displayfieldsInfo = new RepoItemInfo(this, "DisplayFields", ".//ul[#'wstep']/li[@innertext='Display Fields']", 30000, null, "d0c38bdf-b280-4266-8798-59c83c872921");
                _chkdescriptionInfo = new RepoItemInfo(this, "ChkDescription", ".//table[#'profilesettings']//input[@value='description']", 30000, null, "bb4b4c48-a8b6-471d-bfdd-b7f89c390050");
                _chknameInfo = new RepoItemInfo(this, "ChkName", ".//table[#'profilesettings']//input[@value='name']", 30000, null, "214f9a2d-8370-47d0-915c-6962f2a0e0ad");
                _chksourceInfo = new RepoItemInfo(this, "ChkSource", ".//table[#'profilesettings']//input[@value='external id']", 30000, null, "23b56da2-3ea2-434d-81f0-a5d07130263e");
                _chkassignedInfo = new RepoItemInfo(this, "ChkAssigned", ".//table[#'profilesettings']//input[@value='assigned']", 30000, null, "28f85073-9fd4-480c-8379-0c4d309098b6");
                _chkstatusInfo = new RepoItemInfo(this, "ChkStatus", ".//table[#'profilesettings']//input[@value='status']", 30000, null, "8274cdef-6d0d-4888-9944-a96f4c11d2fe");
                _chknotesInfo = new RepoItemInfo(this, "ChkNotes", ".//table[#'profilesettings']//input[@value='notes']", 30000, null, "4911fa53-d93b-4e3e-aa1c-b2ce8a3115ed");
                _chkurlInfo = new RepoItemInfo(this, "ChkUrl", ".//table[#'profilesettings']//input[@value='url']", 30000, null, "4ca5ef77-9075-4c16-b7a2-b68b0b63bef6");
                _buttonnextfieldInfo = new RepoItemInfo(this, "ButtonNextField", ".//table[#'profilesettings']//input[@value='Next']", 30000, null, "68219337-7381-40a8-8764-941564ecd4c7");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fc22f2da-5b10-4547-ac5e-7154d4d27762")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The DisplayFields item.
            /// </summary>
            [RepositoryItem("d0c38bdf-b280-4266-8798-59c83c872921")]
            public virtual Ranorex.LiTag DisplayFields
            {
                get
                {
                    return _displayfieldsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The DisplayFields item info.
            /// </summary>
            [RepositoryItemInfo("d0c38bdf-b280-4266-8798-59c83c872921")]
            public virtual RepoItemInfo DisplayFieldsInfo
            {
                get
                {
                    return _displayfieldsInfo;
                }
            }

            /// <summary>
            /// The ChkDescription item.
            /// </summary>
            [RepositoryItem("bb4b4c48-a8b6-471d-bfdd-b7f89c390050")]
            public virtual Ranorex.InputTag ChkDescription
            {
                get
                {
                    return _chkdescriptionInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkDescription item info.
            /// </summary>
            [RepositoryItemInfo("bb4b4c48-a8b6-471d-bfdd-b7f89c390050")]
            public virtual RepoItemInfo ChkDescriptionInfo
            {
                get
                {
                    return _chkdescriptionInfo;
                }
            }

            /// <summary>
            /// The ChkName item.
            /// </summary>
            [RepositoryItem("214f9a2d-8370-47d0-915c-6962f2a0e0ad")]
            public virtual Ranorex.InputTag ChkName
            {
                get
                {
                    return _chknameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkName item info.
            /// </summary>
            [RepositoryItemInfo("214f9a2d-8370-47d0-915c-6962f2a0e0ad")]
            public virtual RepoItemInfo ChkNameInfo
            {
                get
                {
                    return _chknameInfo;
                }
            }

            /// <summary>
            /// The ChkSource item.
            /// </summary>
            [RepositoryItem("23b56da2-3ea2-434d-81f0-a5d07130263e")]
            public virtual Ranorex.InputTag ChkSource
            {
                get
                {
                    return _chksourceInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkSource item info.
            /// </summary>
            [RepositoryItemInfo("23b56da2-3ea2-434d-81f0-a5d07130263e")]
            public virtual RepoItemInfo ChkSourceInfo
            {
                get
                {
                    return _chksourceInfo;
                }
            }

            /// <summary>
            /// The ChkAssigned item.
            /// </summary>
            [RepositoryItem("28f85073-9fd4-480c-8379-0c4d309098b6")]
            public virtual Ranorex.InputTag ChkAssigned
            {
                get
                {
                    return _chkassignedInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkAssigned item info.
            /// </summary>
            [RepositoryItemInfo("28f85073-9fd4-480c-8379-0c4d309098b6")]
            public virtual RepoItemInfo ChkAssignedInfo
            {
                get
                {
                    return _chkassignedInfo;
                }
            }

            /// <summary>
            /// The ChkStatus item.
            /// </summary>
            [RepositoryItem("8274cdef-6d0d-4888-9944-a96f4c11d2fe")]
            public virtual Ranorex.InputTag ChkStatus
            {
                get
                {
                    return _chkstatusInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkStatus item info.
            /// </summary>
            [RepositoryItemInfo("8274cdef-6d0d-4888-9944-a96f4c11d2fe")]
            public virtual RepoItemInfo ChkStatusInfo
            {
                get
                {
                    return _chkstatusInfo;
                }
            }

            /// <summary>
            /// The ChkNotes item.
            /// </summary>
            [RepositoryItem("4911fa53-d93b-4e3e-aa1c-b2ce8a3115ed")]
            public virtual Ranorex.InputTag ChkNotes
            {
                get
                {
                    return _chknotesInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkNotes item info.
            /// </summary>
            [RepositoryItemInfo("4911fa53-d93b-4e3e-aa1c-b2ce8a3115ed")]
            public virtual RepoItemInfo ChkNotesInfo
            {
                get
                {
                    return _chknotesInfo;
                }
            }

            /// <summary>
            /// The ChkUrl item.
            /// </summary>
            [RepositoryItem("4ca5ef77-9075-4c16-b7a2-b68b0b63bef6")]
            public virtual Ranorex.InputTag ChkUrl
            {
                get
                {
                    return _chkurlInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ChkUrl item info.
            /// </summary>
            [RepositoryItemInfo("4ca5ef77-9075-4c16-b7a2-b68b0b63bef6")]
            public virtual RepoItemInfo ChkUrlInfo
            {
                get
                {
                    return _chkurlInfo;
                }
            }

            /// <summary>
            /// The ButtonNextField item.
            /// </summary>
            [RepositoryItem("68219337-7381-40a8-8764-941564ecd4c7")]
            public virtual Ranorex.InputTag ButtonNextField
            {
                get
                {
                    return _buttonnextfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ButtonNextField item info.
            /// </summary>
            [RepositoryItemInfo("68219337-7381-40a8-8764-941564ecd4c7")]
            public virtual RepoItemInfo ButtonNextFieldInfo
            {
                get
                {
                    return _buttonnextfieldInfo;
                }
            }
        }

        /// <summary>
        /// The SortFieldFolder folder.
        /// </summary>
        [RepositoryFolder("1e482995-a86b-4280-af74-67db3dd98932")]
        public partial class SortFieldFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sortfieldsInfo;
            RepoItemInfo _cbbfieldsInfo;
            RepoItemInfo _btnaddsortfieldInfo;
            RepoItemInfo _taglocationInfo;
            RepoItemInfo _tagstatusInfo;
            RepoItemInfo _tagurlInfo;
            RepoItemInfo _buttonfinishsortfieldsInfo;

            /// <summary>
            /// Creates a new SortField  folder.
            /// </summary>
            public SortFieldFolder(RepoGenBaseFolder parentFolder) :
                    base("SortField", "", parentFolder, 0, null, false, "1e482995-a86b-4280-af74-67db3dd98932", "")
            {
                _sortfieldsInfo = new RepoItemInfo(this, "SortFields", ".//ul[#'wstep']/li[@innertext='Sort Fields']", 30000, null, "418d81cf-9c2c-4f65-a1bb-4cb48fec44ef");
                _cbbfieldsInfo = new RepoItemInfo(this, "CbbFields", ".//select[#'cbbFields']", 30000, null, "8a5fc876-6b50-4d37-b244-700555373305");
                _btnaddsortfieldInfo = new RepoItemInfo(this, "BtnAddSortField", ".//input[#'btnAddSortField']", 30000, null, "e8cfa9b2-d8eb-48dc-858a-99412d95a90f");
                _taglocationInfo = new RepoItemInfo(this, "TagLocation", ".//table[#'profilesettings']/tbody//span[@innertext='Location']", 30000, null, "336de6d9-7ea8-4cef-b004-963b2c9a11d9");
                _tagstatusInfo = new RepoItemInfo(this, "TagStatus", ".//table[#'profilesettings']/tbody//span[@innertext='Status']", 30000, null, "411b53f0-cd6c-4595-8a8c-155bfd51dfdc");
                _tagurlInfo = new RepoItemInfo(this, "TagURL", ".//table[#'profilesettings']/tbody//span[@innertext='URL']", 30000, null, "419b2319-01ce-4606-bf88-7fde3c2bd15c");
                _buttonfinishsortfieldsInfo = new RepoItemInfo(this, "ButtonFinishSortFields", ".//table[#'profilesettings']//input[@value='Finish']", 30000, null, "2004586b-f2f6-4a89-8c92-f32a3cbd1bf0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e482995-a86b-4280-af74-67db3dd98932")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SortFields item.
            /// </summary>
            [RepositoryItem("418d81cf-9c2c-4f65-a1bb-4cb48fec44ef")]
            public virtual Ranorex.LiTag SortFields
            {
                get
                {
                    return _sortfieldsInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The SortFields item info.
            /// </summary>
            [RepositoryItemInfo("418d81cf-9c2c-4f65-a1bb-4cb48fec44ef")]
            public virtual RepoItemInfo SortFieldsInfo
            {
                get
                {
                    return _sortfieldsInfo;
                }
            }

            /// <summary>
            /// The CbbFields item.
            /// </summary>
            [RepositoryItem("8a5fc876-6b50-4d37-b244-700555373305")]
            public virtual Ranorex.SelectTag CbbFields
            {
                get
                {
                    return _cbbfieldsInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbFields item info.
            /// </summary>
            [RepositoryItemInfo("8a5fc876-6b50-4d37-b244-700555373305")]
            public virtual RepoItemInfo CbbFieldsInfo
            {
                get
                {
                    return _cbbfieldsInfo;
                }
            }

            /// <summary>
            /// The BtnAddSortField item.
            /// </summary>
            [RepositoryItem("e8cfa9b2-d8eb-48dc-858a-99412d95a90f")]
            public virtual Ranorex.InputTag BtnAddSortField
            {
                get
                {
                    return _btnaddsortfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnAddSortField item info.
            /// </summary>
            [RepositoryItemInfo("e8cfa9b2-d8eb-48dc-858a-99412d95a90f")]
            public virtual RepoItemInfo BtnAddSortFieldInfo
            {
                get
                {
                    return _btnaddsortfieldInfo;
                }
            }

            /// <summary>
            /// The TagLocation item.
            /// </summary>
            [RepositoryItem("336de6d9-7ea8-4cef-b004-963b2c9a11d9")]
            public virtual Ranorex.SpanTag TagLocation
            {
                get
                {
                    return _taglocationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TagLocation item info.
            /// </summary>
            [RepositoryItemInfo("336de6d9-7ea8-4cef-b004-963b2c9a11d9")]
            public virtual RepoItemInfo TagLocationInfo
            {
                get
                {
                    return _taglocationInfo;
                }
            }

            /// <summary>
            /// The TagStatus item.
            /// </summary>
            [RepositoryItem("411b53f0-cd6c-4595-8a8c-155bfd51dfdc")]
            public virtual Ranorex.SpanTag TagStatus
            {
                get
                {
                    return _tagstatusInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TagStatus item info.
            /// </summary>
            [RepositoryItemInfo("411b53f0-cd6c-4595-8a8c-155bfd51dfdc")]
            public virtual RepoItemInfo TagStatusInfo
            {
                get
                {
                    return _tagstatusInfo;
                }
            }

            /// <summary>
            /// The TagURL item.
            /// </summary>
            [RepositoryItem("419b2319-01ce-4606-bf88-7fde3c2bd15c")]
            public virtual Ranorex.SpanTag TagURL
            {
                get
                {
                    return _tagurlInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The TagURL item info.
            /// </summary>
            [RepositoryItemInfo("419b2319-01ce-4606-bf88-7fde3c2bd15c")]
            public virtual RepoItemInfo TagURLInfo
            {
                get
                {
                    return _tagurlInfo;
                }
            }

            /// <summary>
            /// The ButtonFinishSortFields item.
            /// </summary>
            [RepositoryItem("2004586b-f2f6-4a89-8c92-f32a3cbd1bf0")]
            public virtual Ranorex.InputTag ButtonFinishSortFields
            {
                get
                {
                    return _buttonfinishsortfieldsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ButtonFinishSortFields item info.
            /// </summary>
            [RepositoryItemInfo("2004586b-f2f6-4a89-8c92-f32a3cbd1bf0")]
            public virtual RepoItemInfo ButtonFinishSortFieldsInfo
            {
                get
                {
                    return _buttonfinishsortfieldsInfo;
                }
            }
        }

        /// <summary>
        /// The ActionsPanelsFolder folder.
        /// </summary>
        [RepositoryFolder("d4660e83-bf23-417c-a9b1-47d6d3e8addb")]
        public partial class ActionsPanelsFolder : RepoGenBaseFolder
        {
            DashboardLibraryRepositoryFolders.HeatMapFolder _heatmap;
            DashboardLibraryRepositoryFolders.IndicatorFolder _indicator;
            RepoItemInfo _btnaddfromInfo;
            RepoItemInfo _radindicatortypeInfo;
            RepoItemInfo _txtdisplaynameInfo;
            RepoItemInfo _colorInfo;
            RepoItemInfo _checkallitemsInfo;

            /// <summary>
            /// Creates a new ActionsPanels  folder.
            /// </summary>
            public ActionsPanelsFolder(RepoGenBaseFolder parentFolder) :
                    base("ActionsPanels", "", parentFolder, 0, null, false, "d4660e83-bf23-417c-a9b1-47d6d3e8addb", "")
            {
                _heatmap = new DashboardLibraryRepositoryFolders.HeatMapFolder(this);
                _indicator = new DashboardLibraryRepositoryFolders.IndicatorFolder(this);
                _btnaddfromInfo = new RepoItemInfo(this, "BtnAddFrom", ".//tr[$varNumber]//img[@id='btnAdd']", 30000, null, "9ff75095-8804-4361-ac5b-1c7a8ee43888");
                _radindicatortypeInfo = new RepoItemInfo(this, "RadIndicatorType", ".//table[#'infoSettings']//label[@innertext=' Indicator']/input[@name='radPanelType']", 30000, null, "e6d44ec4-2543-4785-b0f7-14e814729163");
                _txtdisplaynameInfo = new RepoItemInfo(this, "TxtDisplayName", ".//input[#'txtDisplayName']", 30000, null, "95a8a214-ff07-4896-a20a-358bebf5411f");
                _colorInfo = new RepoItemInfo(this, "Color", ".//table[#'colorPickerTable']//td[@title=$varColor]", 30000, null, "6258d458-9a44-4d59-b4b2-598d2ffc5be3");
                _checkallitemsInfo = new RepoItemInfo(this, "checkAllItems", ".//form[#'form1']//a[@innertext='Check All']", 30000, null, "49f22aeb-0f8a-4776-acd6-46bbc2a4ae3a");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d4660e83-bf23-417c-a9b1-47d6d3e8addb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnAddFrom item.
            /// </summary>
            [RepositoryItem("9ff75095-8804-4361-ac5b-1c7a8ee43888")]
            public virtual Ranorex.ImgTag BtnAddFrom
            {
                get
                {
                    return _btnaddfromInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The BtnAddFrom item info.
            /// </summary>
            [RepositoryItemInfo("9ff75095-8804-4361-ac5b-1c7a8ee43888")]
            public virtual RepoItemInfo BtnAddFromInfo
            {
                get
                {
                    return _btnaddfromInfo;
                }
            }

            /// <summary>
            /// The RadIndicatorType item.
            /// </summary>
            [RepositoryItem("e6d44ec4-2543-4785-b0f7-14e814729163")]
            public virtual Ranorex.InputTag RadIndicatorType
            {
                get
                {
                    return _radindicatortypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RadIndicatorType item info.
            /// </summary>
            [RepositoryItemInfo("e6d44ec4-2543-4785-b0f7-14e814729163")]
            public virtual RepoItemInfo RadIndicatorTypeInfo
            {
                get
                {
                    return _radindicatortypeInfo;
                }
            }

            /// <summary>
            /// The TxtDisplayName item.
            /// </summary>
            [RepositoryItem("95a8a214-ff07-4896-a20a-358bebf5411f")]
            public virtual Ranorex.InputTag TxtDisplayName
            {
                get
                {
                    return _txtdisplaynameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtDisplayName item info.
            /// </summary>
            [RepositoryItemInfo("95a8a214-ff07-4896-a20a-358bebf5411f")]
            public virtual RepoItemInfo TxtDisplayNameInfo
            {
                get
                {
                    return _txtdisplaynameInfo;
                }
            }

            /// <summary>
            /// The Color item.
            /// </summary>
            [RepositoryItem("6258d458-9a44-4d59-b4b2-598d2ffc5be3")]
            public virtual Ranorex.TdTag Color
            {
                get
                {
                    return _colorInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Color item info.
            /// </summary>
            [RepositoryItemInfo("6258d458-9a44-4d59-b4b2-598d2ffc5be3")]
            public virtual RepoItemInfo ColorInfo
            {
                get
                {
                    return _colorInfo;
                }
            }

            /// <summary>
            /// The checkAllItems item.
            /// </summary>
            [RepositoryItem("49f22aeb-0f8a-4776-acd6-46bbc2a4ae3a")]
            public virtual Ranorex.ATag checkAllItems
            {
                get
                {
                    return _checkallitemsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The checkAllItems item info.
            /// </summary>
            [RepositoryItemInfo("49f22aeb-0f8a-4776-acd6-46bbc2a4ae3a")]
            public virtual RepoItemInfo checkAllItemsInfo
            {
                get
                {
                    return _checkallitemsInfo;
                }
            }

            /// <summary>
            /// The HeatMap folder.
            /// </summary>
            [RepositoryFolder("f4111e33-6dfd-4247-b530-f6bb85f02866")]
            public virtual DashboardLibraryRepositoryFolders.HeatMapFolder HeatMap
            {
                get { return _heatmap; }
            }

            /// <summary>
            /// The Indicator folder.
            /// </summary>
            [RepositoryFolder("51c002cf-65d0-47f8-90f0-1e4a19539179")]
            public virtual DashboardLibraryRepositoryFolders.IndicatorFolder Indicator
            {
                get { return _indicator; }
            }
        }

        /// <summary>
        /// The HeatMapFolder folder.
        /// </summary>
        [RepositoryFolder("f4111e33-6dfd-4247-b530-f6bb85f02866")]
        public partial class HeatMapFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cbbcategoryfieldInfo;
            RepoItemInfo _radheatmaptypeInfo;
            RepoItemInfo _cbbseriesfieldInfo;
            RepoItemInfo _cbbseriesvalueInfo;
            RepoItemInfo _radheatvaluedefaultInfo;
            RepoItemInfo _txtcolorInfo;

            /// <summary>
            /// Creates a new HeatMap  folder.
            /// </summary>
            public HeatMapFolder(RepoGenBaseFolder parentFolder) :
                    base("HeatMap", "", parentFolder, 0, null, false, "f4111e33-6dfd-4247-b530-f6bb85f02866", "")
            {
                _cbbcategoryfieldInfo = new RepoItemInfo(this, "CbbCategoryField", ".//select[#'cbbCategoryField']", 30000, null, "ba2c211e-3ad8-4b47-96b8-803ac11ec7f4");
                _radheatmaptypeInfo = new RepoItemInfo(this, "RadHeatMapType", ".//table[#'infoSettings']//label[@innertext=' Heat Map']/input[@name='radPanelType']", 30000, null, "c70263a8-fbbd-4731-906a-56473ae614c1");
                _cbbseriesfieldInfo = new RepoItemInfo(this, "CbbSeriesField", ".//select[#'cbbSeriesField']", 30000, null, "4b4d88ba-76b8-426a-a964-95d05f2f8f8f");
                _cbbseriesvalueInfo = new RepoItemInfo(this, "CbbSeriesValue", ".//select[#'cbbSeriesValue']", 30000, null, "257d62b8-2e9d-4248-bc69-e73149adfd65");
                _radheatvaluedefaultInfo = new RepoItemInfo(this, "RadHeatValueDefault", ".//input[#'radHeatValue_default']", 30000, null, "66d716ff-c3ce-4dd7-891d-5b0d34ca8d60");
                _txtcolorInfo = new RepoItemInfo(this, "txtColor", ".//input[#'txtColor']", 30000, null, "8f44a469-171b-4944-b299-9566e29cff3b");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f4111e33-6dfd-4247-b530-f6bb85f02866")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CbbCategoryField item.
            /// </summary>
            [RepositoryItem("ba2c211e-3ad8-4b47-96b8-803ac11ec7f4")]
            public virtual Ranorex.SelectTag CbbCategoryField
            {
                get
                {
                    return _cbbcategoryfieldInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbCategoryField item info.
            /// </summary>
            [RepositoryItemInfo("ba2c211e-3ad8-4b47-96b8-803ac11ec7f4")]
            public virtual RepoItemInfo CbbCategoryFieldInfo
            {
                get
                {
                    return _cbbcategoryfieldInfo;
                }
            }

            /// <summary>
            /// The RadHeatMapType item.
            /// </summary>
            [RepositoryItem("c70263a8-fbbd-4731-906a-56473ae614c1")]
            public virtual Ranorex.InputTag RadHeatMapType
            {
                get
                {
                    return _radheatmaptypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RadHeatMapType item info.
            /// </summary>
            [RepositoryItemInfo("c70263a8-fbbd-4731-906a-56473ae614c1")]
            public virtual RepoItemInfo RadHeatMapTypeInfo
            {
                get
                {
                    return _radheatmaptypeInfo;
                }
            }

            /// <summary>
            /// The CbbSeriesField item.
            /// </summary>
            [RepositoryItem("4b4d88ba-76b8-426a-a964-95d05f2f8f8f")]
            public virtual Ranorex.SelectTag CbbSeriesField
            {
                get
                {
                    return _cbbseriesfieldInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbSeriesField item info.
            /// </summary>
            [RepositoryItemInfo("4b4d88ba-76b8-426a-a964-95d05f2f8f8f")]
            public virtual RepoItemInfo CbbSeriesFieldInfo
            {
                get
                {
                    return _cbbseriesfieldInfo;
                }
            }

            /// <summary>
            /// The CbbSeriesValue item.
            /// </summary>
            [RepositoryItem("257d62b8-2e9d-4248-bc69-e73149adfd65")]
            public virtual Ranorex.SelectTag CbbSeriesValue
            {
                get
                {
                    return _cbbseriesvalueInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbSeriesValue item info.
            /// </summary>
            [RepositoryItemInfo("257d62b8-2e9d-4248-bc69-e73149adfd65")]
            public virtual RepoItemInfo CbbSeriesValueInfo
            {
                get
                {
                    return _cbbseriesvalueInfo;
                }
            }

            /// <summary>
            /// The RadHeatValueDefault item.
            /// </summary>
            [RepositoryItem("66d716ff-c3ce-4dd7-891d-5b0d34ca8d60")]
            public virtual Ranorex.InputTag RadHeatValueDefault
            {
                get
                {
                    return _radheatvaluedefaultInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The RadHeatValueDefault item info.
            /// </summary>
            [RepositoryItemInfo("66d716ff-c3ce-4dd7-891d-5b0d34ca8d60")]
            public virtual RepoItemInfo RadHeatValueDefaultInfo
            {
                get
                {
                    return _radheatvaluedefaultInfo;
                }
            }

            /// <summary>
            /// The txtColor item.
            /// </summary>
            [RepositoryItem("8f44a469-171b-4944-b299-9566e29cff3b")]
            public virtual Ranorex.InputTag txtColor
            {
                get
                {
                    return _txtcolorInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The txtColor item info.
            /// </summary>
            [RepositoryItemInfo("8f44a469-171b-4944-b299-9566e29cff3b")]
            public virtual RepoItemInfo txtColorInfo
            {
                get
                {
                    return _txtcolorInfo;
                }
            }
        }

        /// <summary>
        /// The IndicatorFolder folder.
        /// </summary>
        [RepositoryFolder("51c002cf-65d0-47f8-90f0-1e4a19539179")]
        public partial class IndicatorFolder : RepoGenBaseFolder
        {
            RepoItemInfo _editpanelInfo;
            RepoItemInfo _cbbstatfieldInfo;
            RepoItemInfo _cbbstatfieldvalueInfo;
            RepoItemInfo _fromInfo;
            RepoItemInfo _txtcolorInfo;
            RepoItemInfo _newpanelInfo;

            /// <summary>
            /// Creates a new Indicator  folder.
            /// </summary>
            public IndicatorFolder(RepoGenBaseFolder parentFolder) :
                    base("Indicator", "", parentFolder, 0, null, false, "51c002cf-65d0-47f8-90f0-1e4a19539179", "")
            {
                _editpanelInfo = new RepoItemInfo(this, "EditPanel", ".//form[#'form1']//table/tbody/tr/td/a[@innertext=$varDisplayName]//parent::td/following-sibling::td[3]/a[@innertext='Edit']", 30000, null, "3ffbf2f6-8ec1-41f6-8264-6c9a30b995a4");
                _cbbstatfieldInfo = new RepoItemInfo(this, "CbbStatField", ".//select[#'cbbStatField']", 30000, null, "6f47677b-dc78-496c-ae39-3ab03188fbee");
                _cbbstatfieldvalueInfo = new RepoItemInfo(this, "CbbStatFieldValue", ".//select[#'cbbStatFieldValue']", 30000, null, "1d2f257e-bdb9-4940-a20b-9cdd832cfcfc");
                _fromInfo = new RepoItemInfo(this, "From", ".//tr[$varNumber]//input[@id='criteria']", 30000, null, "ccde9df0-61ea-46c1-9a6d-898ae60d0ac8");
                _txtcolorInfo = new RepoItemInfo(this, "TxtColor", ".//tr[$varNumber]//input[@id='txtColor']", 30000, null, "0eaab3a8-1c2f-4390-acb4-fa94af76a37b");
                _newpanelInfo = new RepoItemInfo(this, "NewPanel", ".//form[#'form1']//table/tbody//a[@innertext=$varDisplayName]", 30000, null, "e5a48cbc-f20b-4f0f-90f8-2432325acbfa");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51c002cf-65d0-47f8-90f0-1e4a19539179")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EditPanel item.
            /// </summary>
            [RepositoryItem("3ffbf2f6-8ec1-41f6-8264-6c9a30b995a4")]
            public virtual Ranorex.ATag EditPanel
            {
                get
                {
                    return _editpanelInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The EditPanel item info.
            /// </summary>
            [RepositoryItemInfo("3ffbf2f6-8ec1-41f6-8264-6c9a30b995a4")]
            public virtual RepoItemInfo EditPanelInfo
            {
                get
                {
                    return _editpanelInfo;
                }
            }

            /// <summary>
            /// The CbbStatField item.
            /// </summary>
            [RepositoryItem("6f47677b-dc78-496c-ae39-3ab03188fbee")]
            public virtual Ranorex.SelectTag CbbStatField
            {
                get
                {
                    return _cbbstatfieldInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbStatField item info.
            /// </summary>
            [RepositoryItemInfo("6f47677b-dc78-496c-ae39-3ab03188fbee")]
            public virtual RepoItemInfo CbbStatFieldInfo
            {
                get
                {
                    return _cbbstatfieldInfo;
                }
            }

            /// <summary>
            /// The CbbStatFieldValue item.
            /// </summary>
            [RepositoryItem("1d2f257e-bdb9-4940-a20b-9cdd832cfcfc")]
            public virtual Ranorex.SelectTag CbbStatFieldValue
            {
                get
                {
                    return _cbbstatfieldvalueInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CbbStatFieldValue item info.
            /// </summary>
            [RepositoryItemInfo("1d2f257e-bdb9-4940-a20b-9cdd832cfcfc")]
            public virtual RepoItemInfo CbbStatFieldValueInfo
            {
                get
                {
                    return _cbbstatfieldvalueInfo;
                }
            }

            /// <summary>
            /// The From item.
            /// </summary>
            [RepositoryItem("ccde9df0-61ea-46c1-9a6d-898ae60d0ac8")]
            public virtual Ranorex.InputTag From
            {
                get
                {
                    return _fromInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The From item info.
            /// </summary>
            [RepositoryItemInfo("ccde9df0-61ea-46c1-9a6d-898ae60d0ac8")]
            public virtual RepoItemInfo FromInfo
            {
                get
                {
                    return _fromInfo;
                }
            }

            /// <summary>
            /// The TxtColor item.
            /// </summary>
            [RepositoryItem("0eaab3a8-1c2f-4390-acb4-fa94af76a37b")]
            public virtual Ranorex.InputTag TxtColor
            {
                get
                {
                    return _txtcolorInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TxtColor item info.
            /// </summary>
            [RepositoryItemInfo("0eaab3a8-1c2f-4390-acb4-fa94af76a37b")]
            public virtual RepoItemInfo TxtColorInfo
            {
                get
                {
                    return _txtcolorInfo;
                }
            }

            /// <summary>
            /// The NewPanel item.
            /// </summary>
            [RepositoryItem("e5a48cbc-f20b-4f0f-90f8-2432325acbfa")]
            public virtual Ranorex.ATag NewPanel
            {
                get
                {
                    return _newpanelInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewPanel item info.
            /// </summary>
            [RepositoryItemInfo("e5a48cbc-f20b-4f0f-90f8-2432325acbfa")]
            public virtual RepoItemInfo NewPanelInfo
            {
                get
                {
                    return _newpanelInfo;
                }
            }
        }

        /// <summary>
        /// The MessageFromWebpageAppFolder folder.
        /// </summary>
        [RepositoryFolder("a89b6eed-e0ff-4f7b-a5ab-2fb683644fd2")]
        public partial class MessageFromWebpageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new MessageFromWebpage  folder.
            /// </summary>
            public MessageFromWebpageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MessageFromWebpage", "/form[@title='Message from webpage']", parentFolder, 30000, null, true, "a89b6eed-e0ff-4f7b-a5ab-2fb683644fd2", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "button[@text='OK']", 30000, null, "f2eb7558-6e1e-4b10-b672-3a8fa265fc05");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a89b6eed-e0ff-4f7b-a5ab-2fb683644fd2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a89b6eed-e0ff-4f7b-a5ab-2fb683644fd2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("f2eb7558-6e1e-4b10-b672-3a8fa265fc05")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("f2eb7558-6e1e-4b10-b672-3a8fa265fc05")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The ChromeppAppFolder folder.
        /// </summary>
        [RepositoryFolder("7a172279-4e8e-493e-bb85-db8abb3a46e0")]
        public partial class ChromeppAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new chromepp  folder.
            /// </summary>
            public ChromeppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("chromepp", "/form[@accessiblename='localhost says']", parentFolder, 30000, null, true, "7a172279-4e8e-493e-bb85-db8abb3a46e0", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//button[@accessiblename='OK']", 30000, null, "1b3d7834-0e29-460e-9586-51de91ddaf33");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7a172279-4e8e-493e-bb85-db8abb3a46e0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7a172279-4e8e-493e-bb85-db8abb3a46e0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("1b3d7834-0e29-460e-9586-51de91ddaf33")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("1b3d7834-0e29-460e-9586-51de91ddaf33")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
