///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The login recording.
    /// </summary>
    [TestModule("e9716486-10c0-4b84-8c23-2e1aae73d85d", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DashboardLibraryRepository repository.
        /// </summary>
        public static DashboardLibraryRepository repo = DashboardLibraryRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            varUserName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUserName;

        /// <summary>
        /// Gets or sets the value of variable varUserName.
        /// </summary>
        [TestVariable("59937eda-4cd2-4a39-96a9-3252aeaae74a")]
        public string varUserName
        {
            get { return _varUserName; }
            set { _varUserName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.loginDashboard.Username' at Center.", repo.TestArchitect.loginDashboard.UsernameInfo, new RecordItemIndex(0));
            repo.TestArchitect.loginDashboard.Username.Click();
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$varUserName' on item 'TestArchitect.loginDashboard.Username'.", repo.TestArchitect.loginDashboard.UsernameInfo, new RecordItemIndex(1));
            repo.TestArchitect.loginDashboard.Username.Element.SetAttributeValue("Value", varUserName);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.loginDashboard.Login' at Center.", repo.TestArchitect.loginDashboard.LoginInfo, new RecordItemIndex(2));
            repo.TestArchitect.loginDashboard.Login.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
