///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreatePage recording.
    /// </summary>
    [TestModule("82535ad2-3e41-4607-860f-5801f4283c79", ModuleType.Recording, 1)]
    public partial class CreatePage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static CreatePage instance = new CreatePage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreatePage()
        {
            pageName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreatePage Instance
        {
            get { return instance; }
        }

#region Variables

        string _pageName;

        /// <summary>
        /// Gets or sets the value of variable pageName.
        /// </summary>
        [TestVariable("697bfc00-0bdf-48dd-82ca-52d2fb6e82c2")]
        public string pageName
        {
            get { return _pageName; }
            set { _pageName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.PageName' at Center.", repo.TestArchitect.PageNameInfo, new RecordItemIndex(0));
            repo.TestArchitect.PageName.Click();
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$pageName' on item 'TestArchitect.PageName'.", repo.TestArchitect.PageNameInfo, new RecordItemIndex(1));
            repo.TestArchitect.PageName.Element.SetAttributeValue("Value", pageName);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.PageOK' at Center.", repo.TestArchitect.PageOKInfo, new RecordItemIndex(2));
            repo.TestArchitect.PageOK.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
