///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsPage
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditPage recording.
    /// </summary>
    [TestModule("09093309-971a-437e-bdf6-0a0f34740207", ModuleType.Recording, 1)]
    public partial class EditPage : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static EditPage instance = new EditPage();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditPage()
        {
            varName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditPage Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varName.
        /// </summary>
        [TestVariable("8c08733c-cea3-4414-85d7-5015227e259f")]
        public string varName
        {
            get { return repo.varName; }
            set { repo.varName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.PageName' at Center.", repo.TestArchitect.PageNameInfo, new RecordItemIndex(0));
            repo.TestArchitect.PageName.Click();
            Delay.Milliseconds(0);
            
            varName = UserCodeUtilities.updateName(varName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$varName' on item 'TestArchitect.PageName'.", repo.TestArchitect.PageNameInfo, new RecordItemIndex(2));
            repo.TestArchitect.PageName.Element.SetAttributeValue("Value", varName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.PageOK' at Center.", repo.TestArchitect.PageOKInfo, new RecordItemIndex(3));
            repo.TestArchitect.PageOK.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
