///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DashboardLibrary.ActionsPanels
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The EditNewPanel recording.
    /// </summary>
    [TestModule("e4323cdc-1f6d-422b-85f6-c0e3f8e2eab5", ModuleType.Recording, 1)]
    public partial class EditNewPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::DashboardLibrary.DashboardLibraryRepository repository.
        /// </summary>
        public static global::DashboardLibrary.DashboardLibraryRepository repo = global::DashboardLibrary.DashboardLibraryRepository.Instance;

        static EditNewPanel instance = new EditNewPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public EditNewPanel()
        {
            varDisplayName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static EditNewPanel Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varDisplayName.
        /// </summary>
        [TestVariable("b472c6fe-35b8-408a-b3c2-4ec395edcf46")]
        public string varDisplayName
        {
            get { return repo.varDisplayName; }
            set { repo.varDisplayName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.ActionsPanels.Indicator.EditPanel' at Center.", repo.TestArchitect.ActionsPanels.Indicator.EditPanelInfo, new RecordItemIndex(0));
            repo.TestArchitect.ActionsPanels.Indicator.EditPanel.Click();
            Delay.Milliseconds(0);
            
            varDisplayName = UserCodeUtilities.updateName(varDisplayName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to '$varDisplayName' on item 'TestArchitect.ActionsPanels.TxtDisplayName'.", repo.TestArchitect.ActionsPanels.TxtDisplayNameInfo, new RecordItemIndex(2));
            repo.TestArchitect.ActionsPanels.TxtDisplayName.Element.SetAttributeValue("Value", varDisplayName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TestArchitect.PageOK' at Center.", repo.TestArchitect.PageOKInfo, new RecordItemIndex(3));
            repo.TestArchitect.PageOK.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'TestArchitect.ActionsPanels.Indicator.NewPanel'.", repo.TestArchitect.ActionsPanels.Indicator.NewPanelInfo, new RecordItemIndex(4));
            Validate.Exists(repo.TestArchitect.ActionsPanels.Indicator.NewPanelInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
